apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-url-kdsv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-url-kdsv
    app.kubernetes.io/part-of: test-app-nntk
  name: build-suite-test-component-image-url-kdsv
  namespace: build-e2e-specific-image-url-rcxs
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: build-suite-test-component-image-url-kdsv
    weight: 100
status: {}
