apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: build-suite-test-component-image-url-kdsv
  namespace: build-e2e-specific-image-url-rcxs
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app-nntk
        appstudio.openshift.io/component: build-suite-test-component-image-url-kdsv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: build-suite-test-component-image-url-kdsv-
      labels:
        appstudio.openshift.io/application: test-app-nntk
        appstudio.openshift.io/component: build-suite-test-component-image-url-kdsv
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: build-e2e-specific-image-url-rcxs
    spec:
      params:
      - name: git-url
        value: https://github.com/psturc-org/devfile-sample-hello-world
      - name: output-image
        value: quay.io/psturc/test-images-protected:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
